OUTNAME_RELEASE = sample_named_dimensions
OUTNAME_DEBUG   = sample_named_dimensions_debug
EXTRA_DIRECTORIES = ../common
SAMPLE_DIR_NAME = $(shell basename $(dir $(abspath $(firstword $(MAKEFILE_LIST)))))
MAKEFILE ?= ../Makefile.config
include $(MAKEFILE)
