OUTNAME_RELEASE = sample_onnx_mnist_coord_conv_ac
OUTNAME_DEBUG   = sample_onnx_mnist_coord_conv_ac_debug
EXTRA_DIRECTORIES = ../common
SAMPLE_DIR_NAME = $(shell basename $(dir $(abspath $(firstword $(MAKEFILE_LIST)))))
MAKEFILE ?= ../Makefile.config
include $(MAKEFILE)
